name: easy_dart_logger
description: A simple and easy to use pure dart logger compatible with dart and Flutter
version: 1.0.2+1
repository: https://github.com/krikristoophe/dart_logger.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.4
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1

dependencies:
  freezed_annotation: ^2.2.0
